apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

  # deployment resources label
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
      
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        # this is place holder
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: 80