kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type }}
  selector:  #labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80